const videos = [
    {
        id: 1,
        title: 'Salaar Telugu Trailer | Prabhas | Prashanth Neel | Prithviraj|Shruthi|',
        thumbnail: 'https://www.sakshi.com/sites/default/files/styles/rich_cards/public/article_images/2023/07/2/salar.jpg?itok=b9MHTi2J',
        likes: 1000,
        views: 10000,
        channel: 'SALAAR ',
        channelLogo: 'https://yt3.googleusercontent.com/ytc/APkrFKYSj1OfdqWSO4X4zCxWYvnVstqnJy-YKSwQ3XxzzA=s176-c-k-c0x00ffffff-no-rj',
      },
      {
        id: 2,
        title: 'TypeScript Tutorial for Beginners [2022] Programming with Mosh via YouTube Help',
        thumbnail: 'https://ccweb.imgix.net/https%3A%2F%2Fimg.youtube.com%2Fvi%2Fd56mG7DezGs%2Fhqdefault.jpg?ar=16%3A9&auto=format&cs=strip&fit=crop&h=380&ixlib=php-4.1.0&w=535&s=660712f4db435db86f8c23c76c854e2f',
        likes: 100,
        views: 1000,
        channel: 'Programming with Mosh',
        channelLogo: 'https://yt3.googleusercontent.com/ebu9ZksIXw0tUWBZd6rtk-It8VGSk8AdfSI_eGR-fl6WGet9LnVPngNQCmjdLJeGXpuylwYInQ=s176-c-k-c0x00ffffff-no-rj',
      },
      {
        id: 3,
        title: '112-ft tall Adiyogi Shiva statue unveiled in Karnataka',
        thumbnail: 'https://kalingatv.com/wp-content/uploads/2023/01/adiyogi-statue.jpg',
        likes: 200,
        views: 50000,
        channel:'Adiyogi',
        channelLogo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Sadhguru-Jaggi-Vasudev.jpg/640px-Sadhguru-Jaggi-Vasudev.jpg',
        
      },
      {
        id: 4,
        title: 'Devara',
        thumbnail: 'https://variety.com/wp-content/uploads/2023/05/Devara1.jpg',
        likes: 10,
        views: 500,
        channel: 'Devara',
        channelLogo: 'https://www.greatandhra.com/newphotos10/devara31704711230.jpg',
      },
      {
        id: 5,
        title: 'Introduction to JavaScript + Setup | JavaScript Tutorial in Hindi #1',
        thumbnail: 'https://cwh-full-next-space.fra1.cdn.digitaloceanspaces.com/videoseries/ultimate-js-tutorial-hindi-1/JS-Thumb.jpg',
        likes: 10,
        views: 15000,
        channel: 'CodeWithHarry',
        channelLogo: 'https://yt3.googleusercontent.com/ytc/APkrFKZGyiFJtoR2Isio_S591bOWpCKBFaIzqSuAG56ubA=s176-c-k-c0x00ffffff-no-rj',
      },
      {
        id: 6,
        title: 'Ayodya ram mandir inaguration by honarable PM on Jan 22nd 2024',
        thumbnail: 'https://staticimg.amarujala.com/assets/images/2024/01/22/750x506/news-of-ayodhya_1705907674.jpeg',
        likes: 200,
        views: 15000,
        channel: 'Ayodya ram mandir',
        channelLogo: 'https://www.peacockride.com/cdn/shop/products/1_d13d649d-cb7f-4945-8e9b-eadd6e31af32_grande.png?v=1678444966',
      },
      {
        id: 7,
        title: 'IAS VS IPS Officers ',
        thumbnail: 'https://i.ytimg.com/vi/uNlLvdnoxeA/maxresdefault.jpg',
        likes: 100,
        views: 180000,
        channel: 'Anurag Aggarwal ',
        channelLogo: 'https://yt3.googleusercontent.com/AZd3lOX5SNLbj1U-sR76YhLkIPYS1mp9OY-sZZeWBFsix7WW2CGiYwbO5SHIwtCY3exbPQrJ=s176-c-k-c0x00ffffff-no-rj',
      },
      {
        id: 8,
        title: 'Full Stack Web Development Course in Telugu | Day 13 | Build Portfolio Project',
        thumbnail: 'https://i.ytimg.com/vi/rkaBFyJX2a0/mqdefault.jpg',
        likes: 10000,
        views: 1000000,
        channel: 'Btechiot Telugu ',
        channelLogo: 'https://yt3.googleusercontent.com/8m5OeQ8PX-inNgirGxNDWr_c383ppIZst7-1qvpqa9Ktpn78aQ7zLc9y6w4ZmLrZtIb6MeWHDw=s176-c-k-c0x00ffffff-no-rj',
      },
      {
        id: 9,
        title: ' 112-ft tall Adiyogi Shiva statue unveiled in Karnataka',
        thumbnail: 'https://kalingatv.com/wp-content/uploads/2023/01/adiyogi-statue.jpg',
        likes: 20000,
        views: 1000000,
        channel: 'Adiyogi  ',
        channelLogo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Sadhguru-Jaggi-Vasudev.jpg/640px-Sadhguru-Jaggi-Vasudev.jpg',
      },
      {
        id: 10,
        title: ' History of Bhimavaram',
        thumbnail: 'https://i.ytimg.com/vi/rkaBFyJX2a0/mqdefault.jpg',
        likes: 10000,
        views: 1000000,
        channel: 'PARASHURAM TALKS ',
        channelLogo: 'https://yt3.googleusercontent.com/ytc/APkrFKYdXVUEOOISfBQIBJ9PnJfMMgvEkZrMq10jF9WH=s176-c-k-c0x00ffffff-no-rj',
      },
      
      {
        id: 11,
        title: ' Job Interview Process at Altisource ft Ravali 1 | EdYoda Alumni Tallks with Rishabh',
        thumbnail: 'https://i.ytimg.com/vi/vd_SJONwQTY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAceEgqb3uAA2_m4eAdCEwWf-MWJA',
        likes: 150000,
        views: 1200000,
        channel: 'EdYoda ',
        channelLogo: 'https://yt3.ggpht.com/ytc/APkrFKbqv3R1PJCM_hN2BxYLDp0KU_GIe2aPiWNcoSP0=s88-c-k-c0x00ffffff-no-rj',
      },
      
      
      {
        id: 12,
        title: ' Breakfast Song | CoComelon Nursery Rhymes & Kids Songs',
        thumbnail: 'https://i.ytimg.com/vi/BEJLI_y6OHE/maxresdefault.jpg',
        likes: 15000,
        views: 180000,
        channel: 'Cocomelon - Nursery Rhymes  ',
        channelLogo: 'https://yt3.googleusercontent.com/ytc/AIf8zZQtdgqoLsOAaZnVnijNPflgiywbpzWTNbwswTghyQ=s176-c-k-c0x00ffffff-no-rj',
      },
      {
        id: 13,
        title: ' Ramp Car Racing - Car Racing 3D - Android Gameplay',
        thumbnail: 'https://i.ytimg.com/vi/GyO1MtLhyt0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCQbutSglZ6qQhCbcy9qvge092szw',
        likes: 20000,
        views: 1000000,
        channel: 'Gaming aadii ',
        channelLogo: 'https://yt3.ggpht.com/XH31zlps9jiqZPwoPvBdKoR2oDF8PKokbepOHaM78kGceaIm-KHMSQkJaumBHP-4mJx8oU2Vhg=s88-c-k-c0x00ffffff-no-rj',
      },
    
      {
        id: 14,
        title: ' CoComelon - Kids Songs and Nursery Rhymes',
        thumbnail: 'https://m.media-amazon.com/images/S/pv-target-images/cf40e2ebc398a3f040cb304974fbc88a873b822c6bb641b99c6533101d1106ed.jpg',
        likes: 11000,
        views: 190000,
        channel: 'Cocomelon - Nursery Rhymes  ',
        channelLogo: 'https://yt3.googleusercontent.com/ytc/AIf8zZQtdgqoLsOAaZnVnijNPflgiywbpzWTNbwswTghyQ=s176-c-k-c0x00ffffff-no-rj',
      },
    
    
      
      {
        id: 15,
        title: ' Mega Ramp Car Stunt Game - Impossible Car Racing Game 3D - Android Gameplay',
        thumbnail: 'https://wallpapers.com/images/hd/bgmi-smoky-character-0251nvedwudnllfe.jpg',
        likes: 11100,
        views: 10000,
        channel: 'BGMI ',
        channelLogo: 'https://globalhindi.in/wp-content/uploads/2023/12/BG2.jpg',
    
      },
      {
        id: 16,
        title: 'TypeScript Tutorial for Beginners [2022] Programming with Mosh via YouTube Help',
        thumbnail: 'https://ccweb.imgix.net/https%3A%2F%2Fimg.youtube.com%2Fvi%2Fd56mG7DezGs%2Fhqdefault.jpg?ar=16%3A9&auto=format&cs=strip&fit=crop&h=380&ixlib=php-4.1.0&w=535&s=660712f4db435db86f8c23c76c854e2f',
        likes: 100,
        views: 1000,
        channel: 'Programming with Mosh',
        channelLogo: 'https://yt3.googleusercontent.com/ebu9ZksIXw0tUWBZd6rtk-It8VGSk8AdfSI_eGR-fl6WGet9LnVPngNQCmjdLJeGXpuylwYInQ=s176-c-k-c0x00ffffff-no-rj',
      },
      {
        id: 17,
        title: 'Salaar Telugu Trailer | Prabhas | Prashanth Neel | Prithviraj|Shruthi|Hombale Films|Vijay Kiragandur',
        thumbnail: 'https://www.sakshi.com/sites/default/files/styles/rich_cards/public/article_images/2023/07/2/salar.jpg?itok=b9MHTi2J',
        likes: 1000,
        views: 10000,
        channel: 'Hombale Films ',
        channelLogo: 'https://yt3.googleusercontent.com/ytc/APkrFKYSj1OfdqWSO4X4zCxWYvnVstqnJy-YKSwQ3XxzzA=s176-c-k-c0x00ffffff-no-rj',
      },
      {
        id: 18,
        title: '10-Hour React Tutorial 2023 - Zero to Advanced | Learn React JS in Hindi',
        thumbnail: 'https://i.ytimg.com/vi/6l8RWV8D-Yo/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBJo44aFPfL6lqBLF99a_1j2q5XFg',
        likes: 200,
        views: 15000,
        channel: 'Coder Dost',
        channelLogo: 'https://yt3.googleusercontent.com/m-FbG7zwy9uuelkhgj4BqkpSGuL29FCDaibjs6P5KmmACUgm5N4iAk2SbJNuHK7dBqUEvSEf=s176-c-k-c0x00ffffff-no-rj',
      },
      {
        id: 19,
        title: 'Off Campus JOB Opportunity 2023 (Geek Olympics) | DSA Free Course | GeeksforGeeks',
        thumbnail: 'https://i.ytimg.com/vi/QavJUSiHFvg/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBuGCSDAQHXiPCF9gww1JkyUTsOaA',
        likes: 10,
        views: 500,
        channel: 'Anshika Gupta',
        channelLogo: 'https://yt3.googleusercontent.com/ytc/APkrFKa3yoeLWJXX30BOAgr75umgoreAWWB3A91YoMd6PDE=s176-c-k-c0x00ffffff-no-rj',
      },
      {
        id: 20,
        title: 'Hyderabad, the city of destiny',
        thumbnail: 'https://www.fabhotels.com/blog/wp-content/uploads/2019/05/Charminar_600.jpg',
        likes: 200,
        views: 50000,
        channel:'Hyderabad',
        channelLogo: 'https://img.veenaworld.com/wp-content/uploads/2022/01/charminar.jpg',
      },
];

    export default videos;